### ISSUE TITLE
Archiv File is not always completely(corrupted) generated! Random Behavior.

### ISSUE THREAD

**Issue by iFadi** [ilifau/TestArchiveCreator#11]
After many tests creating archive files, we noticed that the archive file is not always generated as supposed.(corrupted)
This scenario happens, independently if we use the Cronjob (TestArchiveCron) or try create the archive file directly.

in our case it generates a ZIP File containing only 2 Files(s.screenshot):

- settings.html
- index.html

We tried diverse plugins settings, to reproduce this behavior.  But couldn't find what triggers it, the ilias.log did not really help, because it starts logging after phantomjs begins rendering the HTML files.

Is this behavior familiar or any idea what might trigger it?

![Bildschirmfoto 2021-06-25 um 09 06 14](https://user-images.githubusercontent.com/1717456/123377589-eba0eb80-d594-11eb-8110-1b3ee359b211.png)

![Bildschirmfoto 2021-06-25 um 09 10 37](https://user-images.githubusercontent.com/1717456/123378408-62d67f80-d595-11eb-8bfd-ce6a49d36dd7.png)

**Comment by fneumann** [comment]
Have you activated "Include Questions" and "Include Answers" in the generation settings.? Because if they are set, at least the folders "questions" and "participants" should exist and also a questions.csv/html and participants.csv/html. All of this is written before the PDF generation starts. What kind of test is it? Perhaps a dynamic test (CTM)? You may also try out the settings "Keep Directory" and "Keep Job Files" to check what actually goes into the PDF rendering process.

**Comment by iFadi** [comment]
Thanks for the hints, we have been testing it now for about 10 Weeks and were not able to reproduce this issue again. I'm not sure what might caused the issue.
