### ISSUE TITLE
Latex/MathJax not rendert in PDF - PhantomJS 1.9.8

### ISSUE THREAD

**Issue by iFadi** [ilifau/TestArchiveCreator#12]
We had a test with 400 Students, we use for the archive TestArchiveCron with PhantomJS 1.9.8. Everything seems to work properly(Images, Fonts) except the rendering for Latex Formula (s.screenshot PDF and HTML)

**generated HTML (Latex is rendered):**
![Bildschirmfoto 2021-08-10 um 13 11 31](https://user-images.githubusercontent.com/1717456/128850392-244ed70c-7ce7-458d-8750-bec9b4c48346.png)

**generated PDF (Latex is NOT rendered):**
![Bildschirmfoto 2021-08-10 um 13 09 54](https://user-images.githubusercontent.com/1717456/128850414-823c1b4c-685f-4059-bf24-a4c6986a4213.png)

**Our MathJax Setting:**
![Bildschirmfoto 2021-08-10 um 13 20 59](https://user-images.githubusercontent.com/1717456/128850718-6115cd6e-7297-4a20-ba0d-50071d145a69.png)

We followed all the [instructions](https://github.com/ilifau/TestArchiveCreator/blob/master-ilias54/README.md), Is there any tipp/advice on how to fix this issue? Thank you.

**Comment by fneumann** [comment]
I see you have only MathJax in the browser configured and MathJax  is taken from the original CDN. The latex rendering may then fail due to two problems:

1) phantomjs may not have access to the CDN URL
2) the time needed for a proper MathJax rendering on a page is higher than the waiting time configured in the TestArchiveCreator plugin for a page load in phantomjs before it is rendered.

The best solution to tackle that problem is to set up a server-side rendering of MathJax and activate that for the purpose of PDF generation in the MathJax Settings of ILIAS. Then the formulars are rendered as SVGs on the server before a page is processed by the PDF generation.

**Comment by fneumann** [comment]
No further reply - seems solved.
